# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'HappyPanda' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 4.0.0'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 4.7'
  pod 'R.swift'
  pod 'ESTabBarController-swift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwiftyJSON', '~> 4.1.0'
  pod 'HandyJSON', '~> 4.2.0'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
#  pod 'RealmSwift'
  pod 'ViewDeck'
  pod 'WCDB.swift', '~> 1.0.7.5'

  # Pods for HappyPanda

end
